### PR TITLE
Push job through sidekiq push

### PR DESCRIPTION
**Pull request by autumncollection**
I had two problems:

 - requeue jobs has been returned into default queue
 - i use Sinatra for Sidekiq and there is no need for loading jobs files into Sidekiq::Web, Sidekiq::Client.push is better option then for requeue jobs

### CODE REVIEW

**Comment by autumncollection** [comment]
@twonegatives

**Comment by twonegatives** [comment]
@autumncollection thanks for contribution!
I'll give it a look later this week

**Comment by twonegatives** [comment]
@autumncollection 
> i use Sinatra for Sidekiq and there is no need for loading jobs files into Sidekiq::Web
does it mean your PR changed something related to UI/web logics?

**Comment by autumncollection** [comment]
> @autumncollection
> 
> > i use Sinatra for Sidekiq and there is no need for loading jobs files into Sidekiq::Web
> 
> does it mean your PR changed something related to UI/web logics?

I changed this line regading to https://github.com/mperham/sidekiq/wiki/The-Basics#client:

`record['class'].constantize.perform_async(*record['args'])`

that means, that you must have required all job classes .

Otherwise, if we'll use sidekiq.push method:

`Sidekiq::Client.push(create_options(record))`

you don't need to require jobs, because Sidekiq take class parameter also as a String.

**Comment by twonegatives** [comment]
okay so actually nothing related to UI happens here...
thanks for contribution, hope it works fine now

**Pull request merged**
